# Generated by Django 4.2.3 on 2023-07-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("contenido", models.CharField(max_length=50)),
                ("imagen", models.ImageField(upload_to="servicio")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "servicio", "verbose_name_plural": "servicios",},
        ),
    ]
